name: Build documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/source/**'
      - '.github/workflows/build_documentation.yml'

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: hf-leaderboards-documentation
      package_name: leaderboards
      languages: en
      custom_container: huggingface/leaderboards
      additional_args: --not_python_module
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
