name: Build PR Documentation

on:
  pull_request:
    paths:
      - 'docs/source/**'
      - 'assets/**'
      - '.github/workflows/build_pr_documentation.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@main
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: hf-leaderboards-documentation
      package_name: leaderboards
      languages: en
      custom_container: huggingface/leaderboards
      additional_args: --not_python_module
  